name: Build repo
on:
  workflow_dispatch:

jobs:
  build:
    name: Build repo
    runs-on: ubuntu-latest
    steps:
      - name: Install Cache::Cache
        run: sudo apt-get install -y libcache-cache-perl
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run buildrepo.pl
        run: |
          perl buildrepo.pl
      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -a -m "Release ${{ github.event.inputs.version }}"
          git push
